name: deploy
on:
  push:
    branches:
      - 'master'
    paths:
      - 'src/**'
      - 'package.json'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm i
    - name: Configure GitHub user
      run: |
        git config --global user.email "beata.detkova.jr@gmail.com"
        git config --global user.name "Beata Detkova"
    - name: Deployment to GitHub Pages
      run: npm run deploy